### ISSUE TITLE
A Template Engine for generating python3 code.

### ISSUE THREAD

**Issue by taeguk** [DrawML/research-ml#2]
We need a template engine for generating python3 code.
Does it exist?
We need to search about this...
If there is not exist, we need to develop this, too...:(

**Comment by ovekyc** [comment]
I found about the template engine which mentioned by taeguk but i didnt find it
I think, however, it is enough to use HTML template engine for DrawML at least before Neural Net
But im not sure it is enough for NN too, specially in like adding layer or somthing
So i decide to make a transform script with Jinja2 and xml.etree.ElementTree

See detail
<del>https://docs.python.org/2/library/xml.etree.elementtree.html</del> **(we'll use python3)**
https://docs.python.org/3.2/library/xml.etree.elementtree.html
http://jinja.pocoo.org/docs/dev/

**Comment by taeguk** [comment]
How about my new idea?

Make template code complete executable library module. And then, we execute it by calling function with parameters parsed from xml.
See below as a example.

``` python3
# FILE : template_linear_regression.py
def main(param1, param2, .......many params......):
    ~~~~~~~
```

``` python3
# FILE : linear_regression.py
# parsing xml
from template_linear_regression import main
main(......params parsed from xml......)
```

I think,

## Pros
1. Safety.
2. We can split the codes and merge similar functions in one file. So, the codes will be well-structuralized.

## Cons
1. Codes will be changed to be long.

**Comment by Gnob** [comment]
@taeguk It's interesting. but i think we will discuss the new idea tomorrow, not now.

**Comment by taeguk** [comment]
Temporarily, we use jinja2
