### ISSUE TITLE
About XML

### ISSUE THREAD

**Issue by ovekyc** [DrawML/research-ml#4]
There is two agenda in this issue
First, naming rule and the last one is format

We decided that the naming rule should be underscore method
but i think it is inefficient bcz of the tensorflow
Tensorflow has own functions what named already
So we have to bind our name to tensorflow name on somewhere in our service, if we name the attributes of XML different with tensorflow
For example, suppose that our optimizer name is gradient_descent and tensorflow's optimizer name is GradientDescentOptimizer
then we have to bind those two things

The second thing is format
I found some information about XML format which said XML usually use element instead of attribute
They said it is not good using attribute in XML for serveral reasons
(
Some of the problems with attributes are:
attributes cannot contain multiple values (child elements can)
attributes are not easily expandable (for future changes)
attributes cannot describe structures (child elements can)
attributes are more difficult to manipulate by program code
attribute values are not easy to test against a DTD
)
but there is no certain rule using XML so we have to decide some way to use it

**Comment by taeguk** [comment]
My opinion to first agenda.

I think we have to make binding between our naming and tensorflow naming.
If we fit our naming to tensorflow, we will be comfortable. 
But, a flexibility will be degraded. If we do that, we are hard to change our naming or structures.
So I think binding is needed even if we can fit our naming to tensorflow.
If we adopt my opinion, "How to bind naming efficient?" will be new issue to us.

**Comment by taeguk** [comment]
My opinion to second agenda.

I agree that informations.
I try to change my template.xml followed that guides.
https://github.com/DrawML/research-ml/tree/master/taeguk/linear_regression
I think first thing(original) is more readable, but second thing(new) is more expandable.

**Comment by koohanmo** [comment]
First issue, it is more comfortable to implement our project. @taeguk worry about flexibility, but if we will use only tensorflow, it's not worry.
Second issue ,  in our project, i think it just policy.

**Comment by taeguk** [comment]
1. binding
2. tag, not attribute
