### ISSUE TITLE
Using tensorflow's distributed features instead of our task distribution protocol.

### ISSUE THREAD

**Issue by taeguk** [DrawML/research-ml#8]
Now, our design is delivering codes from master to slave and from slave to worker. And worker executes that.
I have a try to think a new design.
It is using tensorflow's distributed features instead of our task delivering protocol.
(https://www.tensorflow.org/versions/r0.10/how_tos/distributed/index.html#distributed-tensorflow)

How do you think?

**Comment by Gnob** [comment]
i can't get it.
how to deliver it by using the feature?
can you explain your idea in detail?

**Comment by taeguk** [comment]
Hmm.. In conclusion, we can't do this way because of the time.
Let's discuss later.

**Comment by taeguk** [comment]
If you want to know, let's read the link above.
If we use this feature, our protocol will be more simple.

**Comment by taeguk** [comment]
I think this issue is not adjusted to research-ml repo.
Let's talk about this issue in research-dist.
